import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from "./providers"
import './globals.css'
import { AuthProvider } from '@/components/AuthProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Safe Tutorial: Passkeys',
  description: 'Generated by create next app'
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div
            style={{
              display: 'flex',
              flexDirection: 'column',
              minHeight: '100vh'
            }}
          >
            {/* Navbar */}
            <nav style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              padding: '1rem 2.5rem',
              borderBottom: '1px solid rgba(0,0,0,0.1)'
            }}>
              <div>
                {/* Logo or brand name can go here */}
              </div>
              <AuthProvider />
            </nav>

            {/* Main content */}
            <main style={{
              flex: 1,
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
              padding: '2.5rem'
            }}>
              {children}
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
