import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from "./providers"
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Safe Tutorial: Passkeys',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              marginLeft: '40px',
              marginRight: '40px',
              flexDirection: 'column',
              minHeight: '100vh'
            }}
          >
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
