import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from "./providers"
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Safe Tutorial: Passkeys',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" style={{ height: "100%" }}>
      <body className={inter.className} style={{ height: "100%" }}>
        <Providers>
          <nav
            style={{
              display: 'flex',
              justifyContent: 'space-between',
              padding: '1rem'
            }}
          >
            <a href="https://safe.global">
              Safe logo 🔐
            </a>
            <div style={{ display: 'flex' }}>
              <a
                href="https://docs.safe.global/home/passkeys-tutorials/safe-passkeys-tutorial"
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  marginRight: '1rem'
                }}
                target="_blank"
                rel="noopener noreferrer"
              >
                Read tutorial ↗️
              </a>
              <a
                href="https://github.com/5afe/safe-passkeys-tutorial"
                style={{ display: 'flex', alignItems: 'center' }}
                target="_blank"
                rel="noopener noreferrer"
              >
                View on GitHub 🐱
              </a>
            </div>
          </nav>
          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              marginLeft: '40px',
              marginRight: '40px',
              flexDirection: 'column'
            }}
          >
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
